[project]
name = "zephyryx-storage-keep"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/zephyryx-storage-keep/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.zephyryx-storage-keep]
path = "contracts/zephyryx-storage-keep.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
